# This configuration is based on:
#   https://docs.travis-ci.com/user/languages/rust/
#   https://doc.rust-lang.org/book/release-channels.html
#   http://johannh.me/blog/rustfmt-ci.html
#
# It doesn't validate at http://lint.travis-ci.org/ or with `travis
# lint` due to https://github.com/travis-ci/travis-yaml/issues/114
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
before_script: (cargo install rustfmt || true)
script:
- |
  cargo fmt -- --write-mode=diff &&
  cargo build --verbose &&
  cargo test --verbose
